server:
  port: 8080
  servlet:
    context-path: /core
  max-http-header-size: 20000

spring:
  application:
    name: core
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: dev



